# Publish all joint states -----------------------------------
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50  
  
# Position Controllers ---------------------------------------
rover_arm_eksen1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
rover_arm_eksen2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
rover_arm_eksen3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
rover_arm_eksen4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
rover_arm_eksen5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
rover_arm_eksen6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}

rover_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains: 
#    joint1: {p: 500,  d: 100, i: 0.001, i_clamp: 1}
#    joint2: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
#    joint3: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
#    joint4: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
#    joint5: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}
#    joint6: {p: 1000,  d: 100, i: 0.001, i_clamp: 1}

    joint1: {p: 1000,  d: 100, i: 0.002, i_clamp: 1}
    joint2: {p: 10000,  d: 100, i: 0.002, i_clamp: 1}
    joint3: {p: 10000,  d: 100, i: 0.002, i_clamp: 1}
    joint4: {p: 1000,  d: 100, i: 0.002, i_clamp: 1}
    joint5: {p: 1000,  d: 100, i: 0.002, i_clamp: 1}
    joint6: {p: 1000,  d: 100, i: 0.002, i_clamp: 1}
  constraints:
    joint1:
      goal: 0.01
    joint2:
      goal: 0.01
    joint3:
      goal: 0.01
    joint4:
      goal: 0.01
    joint5:
      goal: 0.01
    joint6:
      goal: 0.01
  goal_time: 100
